language: erlang
sudo: false
otp_release:
# Test on all supported releases
   - 18.0
   - 17.5
   - 17.4
   - 17.1
   - 17.0

script:
  - make
#  - rebar eunit -v skip_deps=true
  - make plt
  - make dialyze
notifications:
  email: false
